apiVersion: v1
kind: Pod
metadata:
  name: inventory
  labels:
    app: inventory
spec:
  containers:
  - name: inventory
    image: ec2-54-95-48-23.ap-northeast-1.compute.amazonaws.com:5000/dmall/inventory-service:latest
    ports:
    - containerPort: 8080